#!/bin/bash

## Reads File name

echo Enter File name:

read file

echo file

## Creates File

touch $file

echo Touched File "$file" !

## Adds bash prefix

echo '#!/bin/bash' >  "$file"

cat $file

cat << EOF >> $file

chmod +x $file

echo $file is now an executable.



